### PR TITLE
Make `Animation` initializers public

### PR DESCRIPTION
**Pull request by tonybruess**
I'd like to define my own Animation extensions 😃

### CODE REVIEW

**Comment by davdroman** [comment]
Good shout.

I'm AFK right now but I'll merge when I get back in a few hours.

As a side note, if we're going to make these public, would you mind adding some documentation for each one?

**Review by davdroman — APPROVED** [review]

**Review by davdroman — COMMENTED** [review]
@tonybruess can you provide an example of an animation that can't be defined with the currently available APIs?

**Comment by tonybruess** [comment]
I am using shorthand for my custom spring animation:

```
extension Animation {

    public static func customSpring() -> Self {
        .init(
            duration: 0.35,
            timingParameters: UISpringTimingParameters(
                mass: 1.0,
                stiffness: 200,
                damping: 25,
                initialVelocity: CGVector(dx: 15.0, dy: 15.0)
            )
        )
    }
}
```

**Comment by davdroman** [comment]
@tonybruess you can achieve that this way:

```swift
extension Animation {
    public static func customSpring() -> Self {
        .interpolatingSpring(
            mass: 1.0,
            stiffness: 200,
            damping: 25,
            initialVelocity: 15
        )
    }
}
```

Also note the `duration` parameter has no effect on spring animations, so it's not needed :)

**Comment by tonybruess** [comment]
Ah thanks. Yes originally I wanted `.init` to adjust duration but quickly realized it's unused.

Is this PR pointless or do you still want to merge it?

**Comment by davdroman** [comment]
@tonybruess I'll close it for now, I'd like to keep API surface as concise as possible. Thank you for raising this though!

**Pull request closed without merging**
